cloud:
  aws:
    credentials:
      access-key: AKIAUCC4TPBSC5YYKFVM
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: resourceloop-staff-profile-pictures


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090